theme: jekyll-theme-minimal
url: https://midmost.github.io/PoeticCodeForNature/
title: [The title of your site]
description: [A short description of your site's purpose]
logo: [Location of the logo]
show_downloads: ["true" or "false" to indicate whether to provide a download URL]
google_analytics: [Your Google Analytics tracking ID]
